---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***How many customer interviews do we need to do?***

There is not straightforward answer to this question. [Research](https://doi.org/10.1371/journal.pone.0232076) shows that 92% of major themes can be found within 12 interviews. You can stop when you reach “thematic saturation” and <5% of info in an interview is new (but there might be other reasons to do more). Regardless of the problem and customer segment you are working on, expect to do ***at least 5 interviews*** to get any sense of whether your assumptions are correct or not.

***How long should the customer problem interviews be?***

Early conversations are very fast. The chats grow longer as you move from the early broad questions (“Is this a real problem?”) toward more specific
product and industry issues. It only takes 5 minutes to learn whether a problem exists and is important.

Learning how someone currently achieves a certain goal or solves a problem is also quick. Soon you’ll find yourself asking questions which are answered with long
stories explaining their workflow, how they spend their time, or what else they’ve tried. You can usually get what you came for in 10-15 minutes, but people love telling stories about themselves, so you can keep this conversation going indefinitely if it’s valuable for you and interesting for them.

To summarize: aim for a meeting of 30 minutes

***Do we need to create a functional prototype?***

Short answer: no. The timespan of this course is too short to expect you to develop a functional demo or prototype. However, what we want you to do is to design a mockup (paper prototype) that you can use to show customers how your product will look like and how it will work. 

***What should we fill in under "Costs"?***

List the operational costs you will incur while taking your product to market. It’s hard to accurately calculate these too far into the future. Instead, focus on the present:

* What will it cost you to interview 30 to 50 customers? (Also think of salary unless you can/want to work for free)

* What will it cost you to build and launch your MVP? (also think of wages of external designers, producers, ... )

* What will your ongoing burn rate look like in terms of both fixed and variable costs? (renting office space, utility costs, ... )